# Generated by Django 3.2.9 on 2021-11-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211116_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='production_contries',
            new_name='production_countries',
        ),
    ]
