# Generated by Django 3.2.9 on 2021-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_crews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crews',
            field=models.ManyToManyField(blank=True, to='movies.Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
    ]
