# Generated by Django 3.2.9 on 2021-11-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_production_contries_movie_production_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(null=True),
        ),
    ]
