# Generated by Django 3.2.9 on 2021-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211118_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='biography',
        ),
        migrations.AddField(
            model_name='crew',
            name='profile_path',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='movies.Crew'),
        ),
    ]
