# Generated by Django 3.2.9 on 2021-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211119_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(null=True, to='movies.Crew'),
        ),
    ]
