# Generated by Django 3.2.9 on 2021-11-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211120_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crews',
            field=models.ManyToManyField(null=True, to='movies.Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, to='movies.Genre'),
        ),
    ]
