# Generated by Django 3.2.9 on 2021-11-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20211122_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='movies.movie')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='similar_movies',
            field=models.ManyToManyField(through='movies.Similarity', to='movies.Movie'),
        ),
    ]
